# Generated by Django 4.2.4 on 2023-08-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0004_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
