# Generated by Django 4.2.4 on 2023-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0005_rename_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
