# Generated by Django 4.2.4 on 2023-08-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0006_survey_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='activate',
            new_name='active',
        ),
    ]
